### PR TITLE
Adding Ghidra

### PR DESCRIPTION
**Pull request by mumbel**
Here is a one liner to add Ghidra in reference to #8

### CODE REVIEW

**Comment by mumbel** [comment]
@mgielda 

Your call if you would like to wait until a 9.2 release comes out with support included.

The current package (9.1.2) from ghidra-sre.org does not include RISC-V.  Support can be added by copying https://github.com/mumbel/ghidra_riscv into <ghidra_9.1.2_PUBLIC>/Ghidra/Processors or by building Ghidra itself from the Ghidra github master branch.

**Comment by mgielda** [comment]
Hi @mumbel, thanks for your contribution! If we are to add this now, we'd have to link to a repo that contains the support, and then when that is merge, do another PR to change the link. Otherwise, we can wait. It's your call, but I don't think we should merge as-is.

**Comment by mumbel** [comment]
I agree, sorry for the 'noise'.  I shouldn't have been so hasty to close 8, I've converted this to a draft for now.  I'll change back upon 9.2 and give you a ping

**Comment by mumbel** [comment]
@mgielda   Yay, 9.2 is finally out and includes RISC-V support

**Comment by mgielda** [comment]
Awesome :)

**Pull request merged**
